# Generated by Django 4.1.7 on 2023-03-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_poll_polls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=100)),
                ('number_of_votes', models.IntegerField(default=0)),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.polls')),
            ],
            options={
                'ordering': ['poll_id'],
            },
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('otp', models.CharField(max_length=300)),
                ('choice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.choices')),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.polls')),
            ],
        ),
    ]
