# Generated by Django 4.1.7 on 2023-03-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_choices_voters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='poll_id',
            new_name='poll',
        ),
        migrations.RenameField(
            model_name='voters',
            old_name='choice_id',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='voters',
            old_name='poll_id',
            new_name='poll',
        ),
    ]
