# Generated by Django 4.1.7 on 2023-03-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_polls_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='end_date',
            field=models.DateTimeField(verbose_name='End Date'),
        ),
    ]
