# Generated by Django 4.1.7 on 2023-03-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_polls_description_alter_polls_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polls',
            options={},
        ),
    ]
