# Generated by Django 4.1.7 on 2023-03-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_polls_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polls',
            options={'ordering': ['-end_date']},
        ),
    ]
