# Generated by Django 4.1.7 on 2023-03-12 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_voters_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voters',
            old_name='otp',
            new_name='otp_timestamp',
        ),
    ]
