# Generated by Django 4.1.7 on 2023-03-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_rename_otp_voters_otp_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='otp_timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
